GET http://localhost:4000/company

###

GET http://localhost:4000/users

###
 
POST http://localhost:4000/login
Content-Type: application/json

{
    "login":"vitinhomarcelo21@gmail.com",
    "password":"WhiteF0x"
}
### 

POST http://localhost:4000/logout
Content-Type: application/json


###
post http://localhost:4000/usercreate 
Content-Type: application/json

{
    "name":"marcelo",
    "password":"WhiteF0x",
    "login": "marcelinho@gmail.com"
}

###
get http://localhost:4000/allusers 
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJjb21wYW55IjoxLCJvcGVyYXRvciI6dHJ1ZSwibWFuYWdlciI6ZmFsc2UsIm9wZXJhdGlvbmFsIjpmYWxzZSwiaWF0IjoxNjYzODY2NDA2LCJleHAiOjE2NjM4NzAwMDZ9.WDwag0huhIEEZyrxpk_fo1Emz6saymte78mVk2TOiTY

###